In [27]:
from LocalSQLConnection import run_query

ImportError: cannot import name 'run_query' from 'LocalSQLConnection' (C:\Users\anshu\OneDrive\Documents\GitHub\1602668743_SQLFiles_Tier_1_updated_10_13_2020\SQLFiles_Tier_1\LocalSQLConnection.py)

In [23]:
import sqlite3
import pandas as pd

def run_query(query):
    conn = sqlite3.connect('sqlite_db_pythonsqlite.db')  # <- path may need to change
    result = pd.read_sql_query(query, conn)
    conn.close()
    return result

In [25]:
run_query("SELECT name FROM sqlite_master WHERE type='table';")

         name
0    Bookings
1  Facilities
2     Members

In [29]:
query10 = """
SELECT f.name AS facility_name,
       SUM(
         CASE 
           WHEN b.memid = 0 THEN b.slots * f.guestcost
           ELSE b.slots * f.membercost
         END
       ) AS total_revenue
FROM Bookings b
JOIN Facilities f ON b.facid = f.facid
GROUP BY f.name
HAVING total_revenue < 1000;
"""

run_query(query10)

   facility_name  total_revenue
0     Pool Table            270
1  Snooker Table            240
2   Table Tennis            180

In [37]:
query11 = """
SELECT 
m.firstname || ' '||  m.surname AS member_name,
r.firstname || ' ' || r.surname AS recommended_by
FROM Members m
LEFT JOIN Members r ON m.recommendedby = r.memid
ORDER BY m.surname, m.firstname;
"""
run_query(query11)

                member_name     recommended_by
0            Florence Bader    Ponder Stibbons
1                Anne Baker    Ponder Stibbons
2             Timothy Baker     Jemima Farrell
3                Tim Boothe         Tim Rownam
4            Gerald Butters       Darren Smith
5               Joan Coplin      Timothy Baker
6             Erica Crumpet        Tracy Smith
7                Nancy Dare    Janice Joplette
8             David Farrell               None
9            Jemima Farrell               None
10              GUEST GUEST               None
11          Matthew Genting     Gerald Butters
12                John Hunt  Millicent Purview
13              David Jones    Janice Joplette
14            Douglas Jones        David Jones
15          Janice Joplette       Darren Smith
16           Anna Mackenzie       Darren Smith
17             Charles Owen       Darren Smith
18             David Pinker     Jemima Farrell
19        Millicent Purview        Tracy Smith
20               Tim Rownam               None
21         Henrietta Rumney    Matthew Genting
22         Ramnaresh Sarwin     Florence Bader
23             Darren Smith               None
24             Darren Smith               None
25               Jack Smith       Darren Smith
26              Tracy Smith               None
27          Ponder Stibbons       Burton Tracy
28             Burton Tracy               None
29      Hyacinth Tupperware               None
30  Henry Worthington-Smyth        Tracy Smith

In [39]:
query12 = """
SELECT f.name AS facility_name,
COUNT(b.bookid) AS total_member_bookings
FROM Bookings b
JOIN Facilities f
ON b.facid = f.facid
WHERE b.memid <> 0
GROUP BY f.name
ORDER BY total_member_bookings DESC;
"""
run_query(query12)

     facility_name  total_member_bookings
0       Pool Table                    783
1    Snooker Table                    421
2   Massage Room 1                    421
3     Table Tennis                    385
4  Badminton Court                    344
5   Tennis Court 1                    308
6   Tennis Court 2                    276
7     Squash Court                    195
8   Massage Room 2                     27

In [43]:
query13 = """
SELECT
 f.name AS facility_name,
 strftime('%Y-%m', b.starttime) AS month,
 COUNT(b.bookid) AS member_usage
 FROM Bookings b
 JOIN Facilities f
 ON b.facid = f.facid
 WHERE b.memid <> 0
 GROUP BY f.name, month
 ORDER BY month, facility_name;
 """
run_query(query13)

      facility_name    month  member_usage
0   Badminton Court  2012-07            51
1    Massage Room 1  2012-07            77
2    Massage Room 2  2012-07             4
3        Pool Table  2012-07           103
4     Snooker Table  2012-07            68
5      Squash Court  2012-07            23
6      Table Tennis  2012-07            48
7    Tennis Court 1  2012-07            65
8    Tennis Court 2  2012-07            41
9   Badminton Court  2012-08           132
10   Massage Room 1  2012-08           153
11   Massage Room 2  2012-08             9
12       Pool Table  2012-08           272
13    Snooker Table  2012-08           154
14     Squash Court  2012-08            85
15     Table Tennis  2012-08           143
16   Tennis Court 1  2012-08           111
17   Tennis Court 2  2012-08           109
18  Badminton Court  2012-09           161
19   Massage Room 1  2012-09           191
20   Massage Room 2  2012-09            14
21       Pool Table  2012-09           408
22    Snooker Table  2012-09           199
23     Squash Court  2012-09            87
24     Table Tennis  2012-09           194
25   Tennis Court 1  2012-09           132
26   Tennis Court 2  2012-09           126